OutdoorRD/trails-viz

static/js/line-plot.js
static/js/trail-map.js

These changes link the map and the plot so that when a plot is chosen it is highlighted on the map and when the map is clicked the plot changes accordingly.

Dynamically link map and plot

---

static/js/line-plot.js

Change 'actual' and 'predicted' to 'on-site' and 'modeled'

---

index.html
static/css/style.css
static/js/line-plot.js

Adds annual and monthly average bar charts and functionality to the website such that the user can select which chart they want to view. Also fixes terminology and add labels to the charts. Should close issue #10 and issue #8

Add annual and monthly average bar charts

---

trails-viz-app/src/components/LandingPage.vue

Minor changes to landing page text

---

trails-viz-api/trailsvizapi/app_config.py
trails-viz-api/trailsvizapi/controller/projects.py
trails-viz-api/trailsvizapi/repository/prepare_data.py
trails-viz-api/trailsvizapi/repository/projects_and_sites.py
trails-viz-app/src/App.vue
trails-viz-app/src/components/BarGraph.vue
trails-viz-app/src/components/DemographicsSummary.vue
trails-viz-app/src/components/HomeLocations.vue
trails-viz-app/src/components/HomeLocationsMap.vue
trails-viz-app/src/components/InfoViewer.vue
trails-viz-app/src/components/LandingPage.vue
trails-viz-app/src/components/MapDiv.vue
trails-viz-app/src/components/TimeSeries.vue
trails-viz-app/src/components/TopBar.vue
trails-viz-app/src/store/index.js

closes #63 
closes #59
closes #56

human readable project names and some plot updates

---

trails-viz-app/src/components/LandingPage.vue

More minor changes to landing page layout

---

README.md
docker-conf/default.conf

* Add build badge to readme
* update nginx config in docker image to work with vue routes

Nginx config update

---

.gitattributes
.travis.yml
build.sh
trails-viz-api/trailsvizapi/__init__.py
trails-viz-app/package-lock.json
trails-viz-app/package.json

Auto build

---

trails-viz-api/trailsvizapi/config/app_config.py
trails-viz-api/trailsvizapi/controller/home_locations.py
trails-viz-api/trailsvizapi/controller/projects.py
trails-viz-api/trailsvizapi/repository/home_locations.py
trails-viz-api/trailsvizapi/repository/prepare_data.py
trails-viz-api/trailsvizapi/repository/projects_and_sites.py
trails-viz-app/src/assets/styles/home-locations-map.css
trails-viz-app/src/components/BarGraph.vue
trails-viz-app/src/components/Dashboard.vue
trails-viz-app/src/components/HomeLocationsMap.vue
trails-viz-app/src/components/TimeSeries.vue
trails-viz-app/src/store/index.js

closes #70 
closes #84
closes #90

Multi level home locations

---

trails-viz-api/trailsvizapi/config/app_config.py

rename DOI to DOI_PIL #93

---

docker-conf/default.conf
trails-viz-api/requirements.txt
trails-viz-api/trailsvizapi/__init__.py
trails-viz-api/trailsvizapi/config/app_config.py
trails-viz-api/trailsvizapi/config/auth.py
trails-viz-api/trailsvizapi/controller/projects.py
trails-viz-api/trailsvizapi/controller/users_controller.py
trails-viz-api/trailsvizapi/repository/users_repository.py
trails-viz-app/src/App.vue
trails-viz-app/src/components/Login.vue
trails-viz-app/src/components/MapDiv.vue
trails-viz-app/src/components/TopBar.vue
trails-viz-app/src/components/UserProfile.vue
trails-viz-app/src/cookie.js
trails-viz-app/src/main.js
trails-viz-app/src/router.js
trails-viz-app/src/store/index.js

https and authentication

---

Dockerfile

Should fix the issue of running on https

expose https port in Dockerfile

---

docker-conf/default.conf

should fix the issue of http redirecting to localhost https

remove localhost server name from docker conf

---

trails-viz-api/trailsvizapi/config/app_config.py
trails-viz-app/src/components/BarGraph.vue

update king county data sources to display

---

trails-viz-api/trailsvizapi/config/app_config.py

Add OKW NVUM project with GFA and WILD sub-projects

---

docker-conf/default.conf
trails-viz-app/src/components/LandingPage.vue
trails-viz-app/src/components/TopBar.vue

Also changing the taglines on the landing page and topbar (banner).
@vivekkr12, will you please check that I didn't break anything with these changes? We're rebranding and want to get this new name on the dashboard. (FYI I know this won't change the url... I'll create an issue so we can do that later).
Thanks!

Changing the name of the dashboard from "socialtrails" to "TrailTrends"

---

trails-viz-api/trailsvizapi/config/auth.py
trails-viz-api/trailsvizapi/controller/users_controller.py
trails-viz-api/trailsvizapi/repository/users_repository.py
trails-viz-app/package-lock.json
trails-viz-app/package.json
trails-viz-app/src/components/Administration.vue
trails-viz-app/src/components/TimeSeries.vue
trails-viz-app/src/components/TopBar.vue
trails-viz-app/src/main.js
trails-viz-app/src/router.js

Page for admin users to add/ edit / delete users

---

trails-viz-api/trailsvizapi/config/app_config.py
trails-viz-app/package-lock.json

1) Modified `app_config.py` to add a project name and project code for Forest Scale project. 
2) Modified `app_config.py` to specify the data columns. 
3) added a note in the [wiki](https://github.com/OutdoorRD/trails-viz/wiki/Adding-New-Project) that a project code in `allsites.geojson` must match the value provided in the `PROJECT_NAMES` dictionary in the `app_config.py`. 
closes #117 
closes #118

addition of forest scale project to the config 

---

trails-viz-app/src/components/MapDiv.vue
trails-viz-app/src/store/constants.js

Mapbox API upgraded to modern styles

---

trails-viz-api/trailsvizapi/config/app_config.py
trails-viz-api/trailsvizapi/repository/estimates.py
trails-viz-app/src/components/BarGraph.vue
trails-viz-app/src/components/TimeSeries.vue
trails-viz-app/src/store/constants.js

- added `AllTrails` to the front and backend to display alltrails data. 
@woodsp, 
Do you have any suggestions for a color for `alltrails`? The screenshot below shows what it is currently set to. But can easily change this if you are thinking a different color would look better.

added new social media platform to the code 

---

Dockerfile
build.sh
trails-viz-api/trailsvizapi/config/app_config.py
trails-viz-api/trailsvizapi/repository/estimates.py
trails-viz-app/src/components/Administration.vue

* Fix build.sh to fail build when lint / install / package fails. (Include `set -e` in each function in addition to shebang)
* Fix minor lint errors in app and api
* Update Dockerfile to use miniconda. This fixes pyproj error. (Conda is much better at handling python packages with `C/C++` dependencies than pip like `numpy`, `geopandas`, etc.)

Fix build errors

---

README.md
trails-viz-api/trailsvizapi/config/app_config.py

in order to improve organisation and better direct links
also a note to test with python pinned at 3.7

Renaming and recoding projects

---

trails-viz-app/src/components/HomeLocationsMap.vue
trails-viz-app/src/components/MapDiv.vue
trails-viz-app/src/store/constants.js

using a custom mapbox style that highlights parks and natural features
and downplays built features
also deactivated street layer
See Issue #138
Fixes #124

Basemap improvements

---

trails-viz-api/trailsvizapi/config/app_config.py

I added the new project code to three places in `app_config.py`, but am not sure if there are other, additional things that need to happen in order to add a new project. Hopefully this at least gets the process started!

Adding South Mountain Loop as a new dashboard to the app_config.py file

---

trails-viz-api/trailsvizapi/config/app_config.py

Paired with [trails-viz-data PR 42](https://github.com/OutdoorRD/trails-viz-data/pull/42)

Removing OKW dashboards to attempt to solve Issue 41 in trails-viz-data

---

trails-viz-api/requirements.txt
trails-viz-api/trailsvizapi/config/app_config.py
trails-viz-api/trailsvizapi/repository/estimates.py
trails-viz-app/src/components/BarGraph.vue
trails-viz-app/src/components/TimeSeries.vue
trails-viz-app/src/store/constants.js

updated api to include BT project name and data columns. BT Issue #18

Updated for BT Dashboard deployment

---

Dockerfile
trails-viz-api/trailsvizapi/repository/estimates.py

Finding some build errors, so opening a PR to test it out.

Build troubleshooting May 2024

---

trails-viz-api/trailsvizapi/repository/estimates.py

1. Add `ebird`, `gravy`, and `reveal` to list of all platforms in `estimates.py`

More KingCo debugging

---

trails-viz-api/trailsvizapi/config/app_config.py

Ensure that KingCo is included when demographics are pulled from the census tracts data.
closes #210

Add KingCo in CENSUS_TRACT_STATES dictionary

---

web-server-conf/default.conf

**DO NOT MERGE INTO MASTER** branch until DNS records for trailtrends.outdoorrd.org has be reconfigured to point to DigitalOcean droplet.

Configure Nginx server name

---

.github/workflows/api_CICD.yml
trails-viz-api/trailsvizapi/__init__.py

Update API CI/CD runner:
`runs-on: ubuntu-latest` from latest to `runs-on: ubuntu-22.04`

Fix python setup in API CI/CD workflow

---

web-server-conf/default.conf

Fix nginx temporary buffer path

---

.github/workflows/app_CICD.yml

Update runner for app CI/CD workflow to ubuntu-22.04

Update runner for app CI/CD workflow

---

trails-viz-api/trailsvizapi/__init__.py
trails-viz-api/trailsvizapi/config/auth.py
trails-viz-api/trailsvizapi/controller/categorical_chatbot_data.py
trails-viz-api/trailsvizapi/repository/categorical_chatbot_data.py
trails-viz-api/trailsvizapi/repository/chatbot_data.py
trails-viz-api/trailsvizapi/repository/home_locations.py
trails-viz-api/trailsvizapi/repository/map_chatbots.py
trails-viz-api/trailsvizapi/repository/prepare_data.py
trails-viz-app/src/assets/styles/c3-charts.css
trails-viz-app/src/components/Dashboard.vue
trails-viz-app/src/components/DemographicsSummary.vue
trails-viz-app/src/components/HomeLocations.vue
trails-viz-app/src/components/HomeLocationsMap.vue
trails-viz-app/src/components/InfoSource.vue

Added a flipped bar chart in the info source tab. The user can select either display mode count or %.
Updated subtabs formatting to fit them all on one line.
Merge together with https://github.com/OutdoorRD/trails-viz-data/pull/80.

Added info source tab
